export const EASING = {
  linear: t => t,
  easeInQuad: t => t * t,
  easeOutQuad: t => 1 - (1 - t) * (1 - t),
  easeInCubic: t => t * t * t,
  easeOutCubic: t => 1 - Math.pow(1 - t, 3),
  easeInOutCubic: t => (t < 0.5 ? 4 * t * t * t : 1 - Math.pow(-2 * t + 2, 3) / 2),
  easeOutQuint: t => 1 - Math.pow(1 - t, 5),
  easeOutBack: t => {
    const c1 = 1.70158, c3 = c1 + 1;
    return 1 + c3 * Math.pow(t - 1, 3) + c1 * Math.pow(t - 1, 2);
  },
  easeOutElastic: t => {
    const c4 = (2 * Math.PI) / 3;
    if (t <= 0) return 0;
    if (t >= 1) return 1;
    return Math.pow(2, -10 * t) * Math.sin((t * 10 - 0.75) * c4) + 1;
  },
};

export function ease(name, t) {
  const fn = EASING[name] || EASING.linear;
  return fn(t < 0 ? 0 : t > 1 ? 1 : t);
}

export const OPTIC_DEFAULTS = {
  holo: {
    kind: 'holo',
    housingColor: 0x1b1e22,
    housingRoughness: 0.42,
    housingMetalness: 0.62,
    lensColor: 0x0d2634,
    lensOpacity: 0.34,
    lensRoughness: 0.06,
    lensDirt: 0.35,
    reticle: { color: 0xff3722, size: 0.006, baseIntensity: 2.6, minIntensity: 0.9, maxIntensity: 4.2 },
    parallax: 0.02,
    occlusionFade: 0.35,
  },
  iron: { kind: 'iron', reticle: null, parallax: 0 },
  scope: {
    kind: 'scope',
    lensColor: 0x10202c,
    lensOpacity: 0.28,
    reticle: { color: 0x120f0d, size: 0.0035, baseIntensity: 1.2, minIntensity: 1.2, maxIntensity: 1.2 },
    parallax: 0.006,
  },
  shotgunRing: {
    kind: 'shotgunRing',
    reticle: { color: 0xff8c1a, size: 0.004, baseIntensity: 2.2, minIntensity: 1.4, maxIntensity: 3.4 },
    parallax: 0.01,
  },
};

export const LASER_DEFAULTS = {
  enabled: true,
  color: 0xff2b2b,
  dotSize: 0.02,
  beamOpacity: 0.16,
  maxDistance: 90,
  surfaceDimming: true,
  visibleInSmoke: 0.6,
};

export const RECOIL_PROFILE = {
  rifle: {
    kick: 0.03, kickYaw: 0.01, recovery: 12, kickRecovery: 10,
    pattern: [[0, 1], [0.35, 1.2], [-0.28, 0.95], [0.5, 1.05], [-0.42, 0.9], [0.2, 0.8]],
    camKick: 0.34, camYaw: 0.22, handJitter: 0.4,
  },
  pistol: {
    kick: 0.055, kickYaw: 0.012, recovery: 14, kickRecovery: 13,
    pattern: [[0, 1], [0.2, 0.8]], camKick: 0.42, camYaw: 0.18, handJitter: 0.55,
  },
  sniper: {
    kick: 0.085, kickYaw: 0.008, recovery: 8, kickRecovery: 7,
    pattern: [[0, 1]], camKick: 0.6, camYaw: 0.12, handJitter: 0.8,
  },
  smg: {
    kick: 0.014, kickYaw: 0.007, recovery: 17, kickRecovery: 16,
    pattern: [[0, 1], [0.2, 0.9], [-0.16, 0.85], [0.24, 0.8], [-0.2, 0.75], [0.12, 0.7], [-0.1, 0.65]],
    camKick: 0.18, camYaw: 0.26, handJitter: 0.28,
  },
  shotgun: {
    kick: 0.1, kickYaw: 0.014, recovery: 9, kickRecovery: 8,
    pattern: [[0, 1]], camKick: 0.62, camYaw: 0.2, handJitter: 0.9,
  },
};

export const WEAPONS = [
  {
    id: 'ak',
    name: 'AK-47',
    slot: 0,
    class: 'rifle',
    auto: true,
    rpm: 600,
    dmg: 34,
    headMul: 2.8,
    mag: 30,
    magSize: 30,
    reserve: 120,
    reloadTime: 2.4,
    spreadHip: 0.026,
    spreadAds: 0.0045,
    adsFov: 58,
    kick: 0.03,
    kickYaw: 0.01,
    speed: 330,
    range: 220,
    casing: true,
    sfx: 'rifle',
    weight: 1.15,
    model: 'rifle',
    recoil: 'rifle',
    optic: { ...OPTIC_DEFAULTS.holo },
    laser: { ...LASER_DEFAULTS, enabled: true },
    sway: { bob: 1.0, swayScale: 1.0, inertia: 1.0, breath: 1.0, runInstability: 1.35 },
    ads: { inTime: 0.24, outTime: 0.19, inCurve: 'easeOutQuint', outCurve: 'easeInOutCubic', sensScale: 0.62, swayScale: 0.22 },
    collision: { probeLength: 1.05, retract: 0.34, rise: 0.09, roll: 0.28, minDistance: 0.34 },
    reload: {
      events: [
        { t: 0.0, event: 'reloadStart' },
        { t: 0.16, event: 'magRelease', sound: 'magOut' },
        { t: 0.42, event: 'magOut', sound: 'magDrop' },
        { t: 0.62, event: 'magIn', sound: 'magIn' },
        { t: 0.78, event: 'boltRelease', sound: 'bolt' },
        { t: 0.94, event: 'ammoCommit' },
        { t: 1.0, event: 'reloadEnd' },
      ],
    },
    lod: { near: 0, mid: 22, far: 60, cull: 120 },
  },
  {
    id: 'deagle',
    name: 'DESERT EAGLE',
    slot: 1,
    class: 'pistol',
    auto: false,
    rpm: 240,
    dmg: 62,
    headMul: 2.4,
    mag: 7,
    magSize: 7,
    reserve: 35,
    reloadTime: 2.0,
    spreadHip: 0.02,
    spreadAds: 0.0035,
    adsFov: 62,
    kick: 0.055,
    kickYaw: 0.012,
    speed: 300,
    range: 150,
    casing: true,
    sfx: 'pistol',
    weight: 0.72,
    model: 'pistol',
    recoil: 'pistol',
    optic: { ...OPTIC_DEFAULTS.iron },
    laser: { ...LASER_DEFAULTS, enabled: false },
    sway: { bob: 1.35, swayScale: 1.2, inertia: 1.3, breath: 1.2, runInstability: 1.5 },
    ads: { inTime: 0.17, outTime: 0.14, inCurve: 'easeOutQuint', outCurve: 'easeInOutCubic', sensScale: 0.7, swayScale: 0.3 },
    collision: { probeLength: 0.55, retract: 0.3, rise: 0.08, roll: 0.26, minDistance: 0.28 },
    reload: {
      events: [
        { t: 0.0, event: 'reloadStart' },
        { t: 0.2, event: 'magRelease', sound: 'magOut' },
        { t: 0.45, event: 'magOut', sound: 'magDrop' },
        { t: 0.66, event: 'magIn', sound: 'magIn' },
        { t: 0.86, event: 'slideRelease', sound: 'bolt' },
        { t: 0.94, event: 'ammoCommit' },
        { t: 1.0, event: 'reloadEnd' },
      ],
    },
    lod: { near: 0, mid: 18, far: 45, cull: 90 },
  },
  {
    id: 'sniper',
    name: 'SNIPER',
    slot: 2,
    class: 'sniper',
    auto: false,
    rpm: 45,
    dmg: 99,
    headMul: 2.0,
    mag: 5,
    magSize: 5,
    reserve: 25,
    reloadTime: 3.1,
    spreadHip: 0.055,
    spreadAds: 0.0002,
    adsFov: 16,
    kick: 0.085,
    kickYaw: 0.008,
    speed: 480,
    range: 400,
    casing: true,
    sfx: 'sniper',
    scope: true,
    weight: 1.6,
    model: 'sniper',
    recoil: 'sniper',
    optic: { ...OPTIC_DEFAULTS.scope },
    laser: { ...LASER_DEFAULTS, enabled: false },
    sway: { bob: 0.8, swayScale: 0.85, inertia: 1.4, breath: 1.6, runInstability: 1.8 },
    ads: { inTime: 0.34, outTime: 0.26, inCurve: 'easeInOutCubic', outCurve: 'easeInOutCubic', sensScale: 0.4, swayScale: 0.12 },
    collision: { probeLength: 1.25, retract: 0.4, rise: 0.1, roll: 0.3, minDistance: 0.4 },
    reload: {
      events: [
        { t: 0.0, event: 'reloadStart' },
        { t: 0.24, event: 'magRelease', sound: 'magOut' },
        { t: 0.5, event: 'magOut', sound: 'magDrop' },
        { t: 0.72, event: 'magIn', sound: 'magIn' },
        { t: 0.86, event: 'boltRelease', sound: 'bolt' },
        { t: 0.95, event: 'ammoCommit' },
        { t: 1.0, event: 'reloadEnd' },
      ],
    },
    lod: { near: 0, mid: 30, far: 70, cull: 150 },
  },
  { id: 'grenade', name: 'GRANADA', slot: 3, class: 'throwable', mag: 0, magSize: 0, weight: 0.4, model: 'grenade' },
  {
    id: 'mp5',
    name: 'MP5-SD',
    slot: 4,
    class: 'smg',
    auto: true,
    rpm: 800,
    dmg: 19,
    headMul: 2.2,
    mag: 30,
    magSize: 30,
    reserve: 150,
    reloadTime: 2.1,
    spreadHip: 0.02,
    spreadAds: 0.006,
    adsFov: 64,
    kick: 0.014,
    kickYaw: 0.007,
    speed: 380,
    range: 120,
    casing: true,
    sfx: 'smg',
    weight: 0.85,
    model: 'smg',
    recoil: 'smg',
    optic: { ...OPTIC_DEFAULTS.holo, reticle: { color: 0x39ff8a, size: 0.005, baseIntensity: 2.4, minIntensity: 0.85, maxIntensity: 3.8 } },
    laser: { ...LASER_DEFAULTS, enabled: true },
    sway: { bob: 1.15, swayScale: 1.05, inertia: 0.9, breath: 1.05, runInstability: 1.25 },
    ads: { inTime: 0.2, outTime: 0.16, inCurve: 'easeOutQuint', outCurve: 'easeInOutCubic', sensScale: 0.68, swayScale: 0.24 },
    collision: { probeLength: 0.8, retract: 0.32, rise: 0.085, roll: 0.27, minDistance: 0.3 },
    reload: {
      events: [
        { t: 0.0, event: 'reloadStart' },
        { t: 0.18, event: 'magRelease', sound: 'magOut' },
        { t: 0.4, event: 'magOut', sound: 'magDrop' },
        { t: 0.6, event: 'magIn', sound: 'magIn' },
        { t: 0.8, event: 'boltRelease', sound: 'bolt' },
        { t: 0.94, event: 'ammoCommit' },
        { t: 1.0, event: 'reloadEnd' },
      ],
    },
    lod: { near: 0, mid: 20, far: 50, cull: 100 },
  },
  {
    id: 'pump',
    name: 'PUMP 12',
    slot: 5,
    class: 'shotgun',
    auto: false,
    rpm: 68,
    dmg: 12,
    headMul: 1.6,
    mag: 6,
    magSize: 6,
    reserve: 32,
    reloadTime: 3.4,
    spreadHip: 0.05,
    spreadAds: 0.042,
    adsFov: 66,
    kick: 0.1,
    kickYaw: 0.014,
    speed: 300,
    range: 60,
    pellets: 8,
    casing: false,
    sfx: 'shotgun',
    weight: 1.35,
    model: 'shotgun',
    recoil: 'shotgun',
    optic: { ...OPTIC_DEFAULTS.shotgunRing },
    laser: { ...LASER_DEFAULTS, enabled: false },
    sway: { bob: 0.95, swayScale: 1.1, inertia: 1.25, breath: 1.1, runInstability: 1.6 },
    ads: { inTime: 0.26, outTime: 0.21, inCurve: 'easeOutQuint', outCurve: 'easeInOutCubic', sensScale: 0.66, swayScale: 0.34 },
    collision: { probeLength: 1.1, retract: 0.36, rise: 0.095, roll: 0.29, minDistance: 0.36 },
    reload: {
      events: [
        { t: 0.0, event: 'reloadStart' },
        { t: 0.3, event: 'shellIn', sound: 'magIn' },
        { t: 0.55, event: 'shellIn', sound: 'magIn' },
        { t: 0.78, event: 'shellIn', sound: 'magIn' },
        { t: 0.92, event: 'ammoCommit' },
        { t: 1.0, event: 'reloadEnd' },
      ],
    },
    lod: { near: 0, mid: 16, far: 40, cull: 80 },
  },
];

export const WEAPON_BY_ID = WEAPONS.reduce((acc, w) => {
  acc[w.id] = w;
  return acc;
}, {});

export const VIEWMODEL = {
  basePos: {
    rifle: { x: 0.17, y: -0.175, z: -0.38 },
    pistol: { x: 0.15, y: -0.17, z: -0.34 },
    sniper: { x: 0.17, y: -0.19, z: -0.42 },
    smg: { x: 0.165, y: -0.172, z: -0.36 },
    shotgun: { x: 0.175, y: -0.182, z: -0.4 },
    grenade: { x: 0.18, y: -0.18, z: -0.3 },
  },
  adsPos: {
    rifle: { x: 0, y: -0.105, z: -0.26 },
    pistol: { x: 0, y: -0.084, z: -0.22 },
    sniper: { x: 0, y: -0.105, z: -0.3 },
    smg: { x: 0, y: -0.092, z: -0.24 },
    shotgun: { x: 0, y: -0.075, z: -0.26 },
  },
  adsAlign: { rifle: 0.105, smg: 0.092, pistol: 0.078, sniper: 0.105, shotgun: 0.077 },
  hipFov: 62,
  limits: { sway: 0.05, inertia: 0.09, breath: 0.012, bob: 0.03, roll: 0.09, pitch: 0.12 },
  curves: { bob: 9.0, breath: 0.55, inertiaDamp: 9, swayDamp: 7 },
  adsHold: { holdDelay: 0.0, breathHold: 0.9 },
};
